language: scala
scala:
- 2.10.6
- 2.11.7
jdk:
- oraclejdk7
- oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - graphviz
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
script:
- sbt ++$TRAVIS_SCALA_VERSION coverage test scalastyle test:scalastyle doc
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/13627e9a6e8fa0dec084 # m-doc/general
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
